import { Avatar, Card, Paper, Stack, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Appbar from '../components/Appbar'
import TabBar from '../components/TabBar'
import styles from '../styles/Home.module.css'

export default function Home() {


const[resolution,setResolution] =useState({width:200,height:200})
const[color,setColor]=useState("#ffffff")
const[txtHeight,setTxtHeight]=useState(80)

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Appbar/>

      <div
      
      >
     <center
    
     >
     <Card  
      
      sx={{
        width:resolution.width,
        height:resolution.height,
        borderRadius:0,
        backgroundColor:color,
        marginTop:"20%",
       
          
        
      }} >
          <div
          
          
          style={{
            width:"100%",
            backgroundColor:'',
            marginTop:txtHeight,
            display:'flex',
            flexDirection:'column',
            alignItems: 'center',
            justifyContent: 'center'

          }}
          
          >
            <div style={{
              display:'flex',
              flexDirection:'row',
              alignItems: 'center',
              justifyContent: 'center',
              columnGap:7
            }}>
        <Avatar sx={{height:25,width:25}}>a</Avatar>
        <Stack spacing={-0.4}>
        <Stack spacing={-1} sx={{textAlign:"left",}}>
        <Typography variant="subtitle1" fontSize={12}>name</Typography>
        <Typography variant="subtitle2" fontSize={10} >Username</Typography>
        </Stack>
        
        </Stack>
        </div>
        <div style={{textAlign:'left'}}>
          <Typography variant="h5" fontSize={15} fontFamily="unset">your text</Typography>
        </div>
        </div>

      </Card>
     </center>
     </div>
      <TabBar resolution={resolution} setResolution={setResolution}
      color={color} setColor={setColor}
      textHeight={{txtHeight,setTxtHeight}}
      
      
      />
    </div>
  )
}
